#!/bin/bash
# 
# chkconfig: - 65 35
# description:  A simple startup script for a unicorn ruby web app
# processname: unicorn-redmine
# pidfile:     /var/run/redmine.pid

prog='unicorn_rails'
app='redmine.delorum.com'
pidfile='/var/run/redmine.pid'
config='/var/www/redmine/config/unicorn.rb'

# Source function library.
. /etc/rc.d/init.d/functions

# Source rvm
if [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then source "/usr/local/rvm/scripts/rvm" ; fi

 
start() {
    echo -n $"Starting $app: "
	unicorn_rails -c $config -E production -D
    retval=$?
	if [ $retval = 0 ]
	then
		echo_success
	else
		echo_failure
	fi
	echo
    return $retval
}

stop() {
    echo -n $"Stopping $app: "
    cat $pidfile | xargs kill -QUIT
    retval=$?
    [ -f ${pidfile} ] && /bin/rm -f ${pidfile}
	if [ $retval = 0 ]
	then
		echo_success
	else
		echo_failure
	fi
	echo
    return $retval
}
 
restart(){
	stop
	sleep 2
	start
}

reload(){
	echo -n $"Reloading $app: "
	cat $pidfile | xargs kill -USR2
	retval=$?
	if [ $retval = 0 ]
	then
		echo_success
	else
		echo_failure
	fi
	echo
	return $retval
}
 
rh_status(){
	status -p ${pidfile} $prog
}
 
case "$1" in
    start)
        start;;
    stop)
        stop;;
    restart)
        restart;;
	reload)
		reload;;
    status)
        rh_status;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 3
esac
